### PR TITLE
Fix/logical operators in node name

### PR DESCRIPTION
**Pull request by vincent-noel**
Here is a fix for the bug where nodes containing an logical operator inside their name where crashing the parser. 

For some reason, it was explicitly forbidden by the definition of varName in logic.py. When removed, everything seems to work. 
I'm not sure why it was there in the first place, so I'm a little worried, but so far it's passing all the tests. Do you remember something about that @pauleve and @aurelien-naldi ?

### CODE REVIEW

**Comment by pauleve** [comment]
Not sure, but this looks like really old code; here is the commit which changed this, not sure what the reason was.. https://github.com/colomoto/pyMaBoSS/commit/c3fd1d7ab66294dd0ddda57e3c16c2a0cc0898ab

@vincent-noel you should probably at the test case for bug #45

**Comment by vincent-noel** [comment]
I also added a check that an identifier is not part of the reserved keywords list (true, false, not, and, or, xor, node).

**Comment by aurelien-naldi** [comment]
This fits with what I said in #45: it looks like this constraint was not really used but I am also wondering if the removal can have some side effects.

If an identifier is "not", "true" or "false", then we have a real problem as these keywords appear in the same place as identifiers. For OR, AND and other operators however the context can remove the ambiguity.

**Comment by vincent-noel** [comment]
I think this restriction was introduced back when we were checking if the formula was valid. 
Now we aren't checking with this parser anymore, and using MaBoSS parser, we shouldn't need it. 

I added the simulation from the issue as a new test case.

**Comment by vincent-noel** [comment]
I included in this PR a small fix for entropy plots

**Comment by vincent-noel** [comment]
I added two more tests : one which test a model with a reserved name, and one which just call the plot entropy. 
Also added a new argument to pie plot to not perform normalization as it is the default now but will change in future matplotlib versions. 

I should merge this in the afternoon if everything is ok with you.

**Comment by aurelien-naldi** [comment]
Sounds great! It will be in a new release in time for the next colomoto image then?

**Comment by vincent-noel** [comment]
Actually, if we explicitly choose not to normalize we get errors due to imprecisions. So the default behaviour is going to be normalizing. 

And yes Aurelien, I'll be creating the release today too. And if I remember correctly it will be automatically integrated to the next image.

**Pull request merged**
